title: jb8
description: Cyber Security/IT
url: https://kakesuperstar.github.io/jb8
author: Jacob Boylan
avatar: https://cdn.britannica.com/99/38699-050-5BC18587/Grigory-Yefimovich-Rasputin.jpg
email: jacobboylan8@gmail.com
location: Acworth, Georgia
timezone: +0000

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-paginate
  - jemoji

google_analytics: UA-163113883-1

exclude:
  - scripts/
  - README.md

permalink: /:year/:month/:day/:title.html

defaults:
  - scope:
      path: ""      
      type: "posts"
    values:
      layout: "post"
      author: "Jacob Boylan"
      image: "avatar.jpg"
      share: true
  - scope:
      path: ""      
      type: "pages"
    values:
      layout: "page"
      author: "Jacob Boylan"
      image: "avatar.jpg"

# Jekyll Remote Theme
# ===================
remote_theme: ngzhio/jekyll-theme-hamilton

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: 
  card: summary
logo: avatar.jpg
social:
  name: Jacob Boylan
  links:
    - https://twitter.com
    - https://github.com
lang: en

# Jekyll Paginate
# ===============
paginate: 10
